[env]
TERM = "alacritty"

[window]
decorations = "Full"
opacity = 1.0
startup_mode = "windowed"
title = "Alacritty"

[window.dimensions]
columns = 80
lines   = 30

[window.padding]
x = 15
y = 15 

[window.position]
x = 600
y = 150

[scrolling]
history = 12000

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Light Italic"

[font.offset]
x = 1
y = 3

[font.glyph_offset]
x = 0
y = 0



[colors.primary]
background= "0x171d23"
foreground= "0xffffff"

[colors.cursor]
text=   "0xfafafa"
cursor= "0x008b94"


[colors.normal]
black=   "0x333f4a"
red=     "0xd95468"
green=   "0x8bd49c"
blue=    "0x539afc"
magenta= "0xb62d65"
cyan=    "0x70e1e8"
white=   "0xb7c5d3"


[colors.bright]
black=   "0x41505e"
red=     "0xd95468"
green=   "0x8bd49c"
yellow=  "0xebbf83"
blue=    "0x5ec4ff"
magenta= "0xe27e8d"
cyan=    "0x70e1e8"
white=   "0xffffff"

[bell]
animation = "EaseOutExpo"
color     = "#C0C5CE"
command   = "None"
duration  = 0

[selection]
save_to_clipboard     = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
vi_mode_style = "None"
thickness = 0.1
blink_interval = 500

[cursor.style]
shape = "Block"
blinking = "Always"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "Quit"
key    = "Q"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key    = "Return"
mods   = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key    = "N"
mods   = "Control"

[[keyboard.bindings]]
action = "Minimize"
key    = "M"
mods   = "Control"

[[keyboard.bindings]]
action = "Paste"
key    = "V"
mods   = "Control"

[[keyboard.bindings]]
action = "Copy"
key    = "C"
mods   = "Control"

[[keyboard.bindings]]
chars = "\u0003"
key    = "C"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key    = "PageUp"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key    = "PageDown"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key    = "Home"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key    = "End"
mods   = "Shift"


[debug]
highlight_damage   = false
log_level          = "Warn"
persistent_logging = false
print_events       = false
render_timer       = false
